runtime: nodejs20

env_variables:
  NODE_ENV: production
  MONGODB_URI: mongodb+srv://anushachatterjee7:tKbrfqmoeLM8uyO7@cluster0.jeth9lp.mongodb.net/ai-life-coach?retryWrites=true&w=majority&appName=Cluster0
  JWT_SECRET: ai-life-coach-super-secret-jwt-key-2024
  OPENAI_API_KEY: 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

automatic_scaling:
  min_instances: 1
  max_instances: 5

resources:
  cpu: 1
  memory_gb: 0.5
